### ISSUE TITLE
Cannot download files from Baidu outside of China

### ISSUE THREAD

**Issue by BrendanDriscoll** [yaolinli/IDC#1]
Hi, it appears to be quite difficult to create a Baidu account and download files from Baidu from outside of China. Would it be possible to make the preprocessed image features and the model checkpoints available via some other cloud storage service, such as Google Drive?

**Comment by yaolinli** [comment]
Hi, I will upload the preprocessed image features and the model checkpoints to the google drive recently.

**Comment by BrendanDriscoll** [comment]
Thank you!

**Comment by yaolinli** [comment]
The google drive link is https://drive.google.com/drive/folders/1lElkMAoNxM47oD9-qhAM88S1AnArC-rL?usp=sharing
I am sorry that it is available only for one month due to the storage fee. Please download it as soon as possible.
